// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ContentImage: typeof import('./components/Content/image.vue')['default']
    ContentInfobox: typeof import('./components/Content/Infobox.vue')['default']
    ContentLink: typeof import('./components/Content/Link.vue')['default']
    ContentWarningbox: typeof import('./components/Content/Warningbox.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
